name: uhura

services:
  client:
    image: 525999333867.dkr.ecr.us-west-1.amazonaws.com/uhura-client:latest
    platform: linux/amd64
    depends_on:
      - service
    links:
      - service
    build:
      context: .
      target: client
      args:
        PACKAGE: uhura-client
    environment:
      NODE_ENV: production
    env_file:
      - ./uhura-client/.env.production
    healthcheck:
      test: ['CMD', 'curl', '-f', '${TF_VAR_client_url}']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '${TF_VAR_client_port}:${TF_VAR_client_port}'
  service:
    image: 525999333867.dkr.ecr.us-west-1.amazonaws.com/uhura-service:latest
    platform: linux/amd64
    depends_on:
      - database
    links:
      - database
    build:
      context: .
      target: service
      args:
        PACKAGE: uhura-service
    environment:
      NODE_ENV: production
    env_file:
      - ./uhura-service/.env.production
    healthcheck:
      test: ['CMD', 'curl', '-f', '${TF_VAR_service_url}/health']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '${TF_VAR_service_port}:${TF_VAR_service_port}'
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${TF_VAR_db_username}
      POSTGRES_PASSWORD: ${TF_VAR_db_password}
      POSTGRES_DB: ${TF_VAR_db_name}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'uhura']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
