name: uhura

services:
  client:
    image: 525999333867.dkr.ecr.us-west-1.amazonaws.com/uhura-client:latest
    depends_on:
      - service
    links:
      - service
    build:
      context: .
      target: client
      args:
        PACKAGE: uhura-client
    environment:
      NODE_ENV: production
    env_file:
      - ./uhura-client/.env.production
    ports:
      - '80:80'
  service:
    image: 525999333867.dkr.ecr.us-west-1.amazonaws.com/uhura-service:latest
    depends_on:
      - database
    links:
      - database
    build:
      context: .
      target: service
      args:
        PACKAGE: uhura-service
    environment:
      NODE_ENV: production
    env_file:
      - ./uhura-service/.env.production
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '3000:3000'
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: uhura
      POSTGRES_PASSWORD: ${UHURA_DATABASE_PASSWORD}
      POSTGRES_DB: uhura
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'uhura']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
