name: uhura

services:
  client:
    depends_on:
      - service
    links:
      - service
    build:
      context: uhura-client/
      target: base
    command: ['sh', '-c', 'npx yarn start']
    environment:
      NODE_ENV: ci
    volumes:
      - ./:/app
    working_dir: /app/uhura-client
    ports:
      - '3001:3000'
  service:
    depends_on:
      - database
    links:
      - database
    build:
      context: uhura-service/
      target: base
    command: ['sh', '-c', 'npx yarn start']
    environment:
      NODE_ENV: ci
    env_file:
      - ./uhura-service/.env.ci
    volumes:
      - ./:/app
    working_dir: /app/uhura-service
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '3000:3000'
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: uhura
      POSTGRES_PASSWORD: uhura
      POSTGRES_DB: uhura
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'uhura']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
