services:
  client:
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
      WATCHPACK_POLLING: true
      WDS_SOCKET_HOST: '127.0.0.1'
      WDS_SOCKET_PORT: 3001
  service:
    command: ['sh', '-c', 'npx yarn start:watch']
    environment:
      NODE_ENV: development
