name: uhura

services:
  service:
    depends_on:
      - db
    links:
      - db
    build:
      context: uhura-service/
      target: base
    command: ['sh', '-c', 'npx yarn start']
    environment:
      NODE_ENV: ci
    volumes:
      - ./:/app
    working_dir: /app/uhura-service
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '3000:3000'
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: uhura
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'root']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
